-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 03:08:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ModCampaign` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ModCampaign` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `ModCampaign` ;

-- -----------------------------------------------------
-- Table `Campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Campaign` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Campaign` (
  `campaignId` INT NOT NULL AUTO_INCREMENT,
  `campaignName` VARCHAR(50) NOT NULL,
  `campaignDetail` VARCHAR(500) NOT NULL,
  `campaignStart` DATETIME NOT NULL,
  `campaignEnd` DATETIME NOT NULL,
  `campaignType` ENUM('Individual', 'Group') NOT NULL,
  `campaignUserLimit` INT NULL,
  `campaignCategory` INT NOT NULL,
  PRIMARY KEY (`campaignId`, `campaignCategory`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `campaignName_UNIQUE` ON `Campaign` (`campaignName` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CampaignCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampaignCategory` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CampaignCategory` (
  `campaignCategoryId` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(50) NOT NULL,
  `categoryTarget` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`campaignCategoryId`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `campaignName_UNIQUE` ON `CampaignCategory` (`categoryName` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Feedback` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Feedback` (
  `feedbackId` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(50) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `date` DATETIME NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `bmi` INT NOT NULL,
  `height` INT NOT NULL,
  `weight` INT NOT NULL,
  `calories` VARCHAR(45) NOT NULL,
  `role` ENUM('Creator', 'Attendess') NOT NULL,
  `healthPlatform` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `User_in_Campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User_in_Campaign` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User_in_Campaign` (
  `userId` INT NOT NULL,
  `campaignId` INT NOT NULL,
  PRIMARY KEY (`userId`, `campaignId`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER 'admin'@'%' IDENTIFIED WITH mysql_native_password BY 'trimitr56';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';
flush privileges;
set time_zone = '+7:00';
set global time_zone = '+7:00';
